name: pingpong-brackets
services:
  web:
    image: node:20-alpine
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    environment:
      CHOKIDAR_USEPOLLING: "1"
      NPM_CONFIG_UPDATE_NOTIFIER: "false"
    ports:
      - "5173:5173"   # Vite dev
      - "4173:4173"   # Vite preview (build)
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0"
